{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d14ebe9d-0e36-486c-8834-9004b510299c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import mediapipe as mp\n",
    "import numpy as np\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import make_pipeline\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "# Gesture Labels\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "gesture_names = {\n",
    "0: \"Fist\",\n",
    "1: \"Open Palm\",\n",
    "2: \"Thumbs Up\",\n",
    "3: \"Victory Sign\"\n",
    "}\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "# Dummy Training Data\n",
    "\n",
    "# Replace with collected samples later\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "X_train = np.random.rand(40, 42)\n",
    "y_train = np.array(\n",
    "[0]*10 +\n",
    "[1]*10 +\n",
    "[2]*10 +\n",
    "[3]*10\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "# Train SVM Model\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "model = make_pipeline(\n",
    "StandardScaler(),\n",
    "SVC(kernel='linear', probability=True)\n",
    ")\n",
    "\n",
    "model.fit(X_train, y_train)\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "# MediaPipe Setup\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "mp_hands = mp.solutions.hands\n",
    "mp_draw = mp.solutions.drawing_utils\n",
    "\n",
    "hands = mp_hands.Hands(\n",
    "static_image_mode=False,\n",
    "max_num_hands=1,\n",
    "min_detection_confidence=0.7,\n",
    "min_tracking_confidence=0.7\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "# Webcam Capture\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "while True:\n",
    "success, frame = cap.read()\n",
    "\n",
    "```\n",
    "if not success:\n",
    "    break\n",
    "\n",
    "# Flip frame for mirror effect\n",
    "frame = cv2.flip(frame, 1)\n",
    "\n",
    "# Convert BGR to RGB\n",
    "rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "# Process frame\n",
    "results = hands.process(rgb_frame)\n",
    "\n",
    "if results.multi_hand_landmarks:\n",
    "\n",
    "    for hand_landmarks in results.multi_hand_landmarks:\n",
    "\n",
    "        # Draw landmarks\n",
    "        mp_draw.draw_landmarks(\n",
    "            frame,\n",
    "            hand_landmarks,\n",
    "            mp_hands.HAND_CONNECTIONS\n",
    "        )\n",
    "\n",
    "        # Extract landmarks\n",
    "        landmark_vector = []\n",
    "\n",
    "        for lm in hand_landmarks.landmark:\n",
    "            landmark_vector.append(lm.x)\n",
    "            landmark_vector.append(lm.y)\n",
    "\n",
    "        # Convert to numpy array\n",
    "        sample = np.array(landmark_vector).reshape(1, -1)\n",
    "\n",
    "        # Predict gesture\n",
    "        prediction = model.predict(sample)[0]\n",
    "\n",
    "        gesture_text = gesture_names[prediction]\n",
    "\n",
    "        # Display prediction\n",
    "        cv2.putText(\n",
    "            frame,\n",
    "            f\"Gesture: {gesture_text}\",\n",
    "            (10, 40),\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,\n",
    "            1,\n",
    "            (0, 255, 0),\n",
    "            2\n",
    "        )\n",
    "\n",
    "# Show frame\n",
    "cv2.imshow(\"Real-Time Hand Gesture Recognition\", frame)\n",
    "\n",
    "# Exit on ESC key\n",
    "if cv2.waitKey(1) & 0xFF == 27:\n",
    "    break\n",
    "```\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "# Cleanup\n",
    "\n",
    "# -----------------------------\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10 (gesture)",
   "language": "python",
   "name": "gesture"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
